<?
$PERM["test"]["2"]="D";
$PERM["returns"]["2"]="D";
$PERM["promotions"]["2"]="D";
$PERM["promotions"]["8"]="W";
$PERM["personal"]["2"]="D";
$PERM["personal"]["8"]="W";
$PERM["payments"]["2"]="D";
$PERM["news"]["2"]="D";
$PERM["news"]["8"]="W";
$PERM["information"]["2"]="D";
$PERM["howtobuy"]["2"]="D";
$PERM["faq"]["2"]="D";
$PERM["delivery"]["2"]="D";
$PERM["contacts"]["2"]="D";
$PERM["about"]["2"]="D";
$PERM["catalog"]["2"]="D";
$PERM["catalog"]["8"]="W";
$PERM["vendors"]["8"]="W";
$PERM["reviews"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>